### ISSUE TITLE
how to get the texture of a gray level image

### ISSUE THREAD

**Issue by Statekeylablin** [mortezamg63/Texture-Segmentation-using-Gabor-Filters#16]
Hello, I want to get the texture of a meat. I've run your code. The background and the meat can be separated clearly. However, what I want is to get the texture of the meat. Could you tell me how to do it with your code. Here is what I get.
![屏幕快照 2020-07-24 下午5 41 21](https://user-images.githubusercontent.com/49443927/88379629-e1e79480-cdd5-11ea-8c9e-5b47b23d977a.png). Thank you very much!

**Comment by mortezamg63** [comment]
Hello,
If I could understand you question, you wanna use the output image to extract the region of meat. Right? if so, it is the solution:

At first, copy image and set 1 for region of interest (ROI) and 0 for other regions, this new image is called **mask image**. 
I assume that the green region is meat (ROI).  Set value 1 for all pixels in green region   and value 0 for the pixels in purple region.

Second, multiply the original image with the mask image to get the meat texture. If your original image is RGB, just multiply each channel of the original image with the mask image. So the purple region show nothing(black color) and the green region shows the meat.

I hope my answer is helpful.
