### ISSUE TITLE
When I run this program, I can’t get results similar to yours

### ISSUE THREAD

**Issue by lyf-123** [mortezamg63/Texture-Segmentation-using-Gabor-Filters#17]
![untitled](https://user-images.githubusercontent.com/57982253/93766098-7fc9d500-fc48-11ea-8b3e-e98e421432f0.jpg)

**Comment by lyf-123** [comment]
Could you please guide me？
thank you very much

**Comment by yamt7** [comment]
can you get same result when you use same code ?i got different result when i use same code

**Comment by lyf-123** [comment]
I have changed some parameters
